/*
 * Gurjit Singh
 * Monday Septmeber 23rd - 2019
 * This program displays the making a pizza program
 */

/**
 *
 * @author sangha
 */
public class frmmakingapizza extends javax.swing.JFrame {

    public frmmakingapizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblThird = new javax.swing.JLabel();
        lblFourth = new javax.swing.JLabel();
        lblFifth = new javax.swing.JLabel();
        lblSixth = new javax.swing.JLabel();
        lblSeventh = new javax.swing.JLabel();
        lblEighth = new javax.swing.JLabel();
        lblNinth = new javax.swing.JLabel();
        lblTenth = new javax.swing.JLabel();
        lblEleventh = new javax.swing.JLabel();
        lblTwelfth = new javax.swing.JLabel();
        btnFirst = new javax.swing.JButton();
        txtFirst = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        txtThird = new javax.swing.JTextField();
        txtFifth = new javax.swing.JTextField();
        txtFourth = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFirst.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        lblFirst.setForeground(new java.awt.Color(0, 150, 0));
        lblFirst.setText("Gurjit's PIZZeria");

        lblSecond.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblSecond.setForeground(new java.awt.Color(0, 150, 0));
        lblSecond.setText("Enter the number and size of the pizza you");

        lblThird.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblThird.setForeground(new java.awt.Color(0, 150, 0));
        lblThird.setText("to order and click Calculate");

        lblFourth.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblFourth.setForeground(new java.awt.Color(0, 150, 0));
        lblFourth.setText("NUMBER OF PIZZAS:");

        lblFifth.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblFifth.setForeground(new java.awt.Color(0, 150, 0));
        lblFifth.setText("Diameter of Pizza (cm):");

        lblSixth.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblSixth.setForeground(new java.awt.Color(0, 150, 0));
        lblSixth.setText("Subtotal:");

        lblSeventh.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblSeventh.setForeground(new java.awt.Color(0, 150, 0));
        lblSeventh.setText("Taxes:");

        lblEighth.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblEighth.setForeground(new java.awt.Color(0, 150, 0));
        lblEighth.setText("Grand Total:");

        lblNinth.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblNinth.setForeground(new java.awt.Color(0, 150, 0));
        lblNinth.setText("Thanks for ordering!");

        lblTenth.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        lblTenth.setForeground(new java.awt.Color(0, 150, 0));

        lblEleventh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N

        lblTwelfth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1bb8a0ddd08fe30cbe250c3f3adb870e.png"))); // NOI18N

        btnFirst.setFont(new java.awt.Font("Perpetua Titling MT", 0, 15)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(0, 150, 0));
        btnFirst.setText("Calculate");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        txtFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstActionPerformed(evt);
            }
        });

        txtSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecondActionPerformed(evt);
            }
        });

        txtThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThirdActionPerformed(evt);
            }
        });

        txtFifth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFifthActionPerformed(evt);
            }
        });

        txtFourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFourthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTwelfth, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(lblFifth))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(lblFourth))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(lblSixth))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(lblSeventh)))
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEighth)
                        .addGap(149, 149, 149)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFifth, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFourth, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThird, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEleventh)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFirst)
                        .addGap(339, 339, 339))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSecond)
                        .addGap(226, 226, 226))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblThird)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblFirst)
                        .addGap(313, 313, 313))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTenth, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblNinth)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblFirst)
                .addGap(18, 18, 18)
                .addComponent(lblSecond)
                .addGap(18, 18, 18)
                .addComponent(lblThird)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFourth)
                                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFifth)
                                    .addComponent(txtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSixth)
                                    .addComponent(txtThird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSeventh)
                                    .addComponent(txtFourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblEleventh, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEighth)
                            .addComponent(txtFifth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnFirst)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTwelfth, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenth, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNinth))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // Declared variables for the program
        double numberofpizzas = Double.parseDouble(txtFirst.getText());
        double diameter = Double.parseDouble(txtSecond.getText());
        
        final double LABOUR = 0.75;
        final double RENT = 0.99;
        final double INGREDIENTS = 0.50;
        
        double subtotal = numberofpizzas * (diameter * INGREDIENTS + LABOUR + RENT);
        double taxes = subtotal * 0.13;
        double grandtotal = subtotal + taxes;
        
        // Taxes round up to two decimal places
        taxes = taxes * 100; 
        taxes = Math.round(taxes); 
        taxes = taxes / 100;
        // Subtotal round up to two decimal places
        subtotal = subtotal * 100;
        subtotal = Math.round(subtotal);
        subtotal = subtotal / 100; 
        // Grandtotal round up to two decimal places
        grandtotal = grandtotal * 100;
        grandtotal = Math.round(grandtotal);
        grandtotal = grandtotal / 100; 
        // This displays the subtotal, taxes, and grandtotal for the order
        txtThird.setText ("$" + subtotal);
        txtFourth.setText ("$" + taxes);
        txtFifth.setText ("$" + grandtotal);
        // This displays a sentence related to the size of the pizza
        if ((diameter >= 1)&&(diameter <= 15)) {
            lblTenth.setText ("We are going to make you a cute little pizza!");    
        }
        else if ((diameter >= 15)&&(diameter <= 40)) {
            lblTenth.setText ("This will be delicious!");
        }
        else if ((diameter >= 40)&&(diameter <= 1000)) {
            lblTenth.setText ("Whoa, big pizza! You might need a truck to get this home!");
        }
        else if (diameter >= 1000) {
            lblTenth.setText ("Whoa, big big pizza! You might need a plane to get this home!");
        }
        
        
    }//GEN-LAST:event_btnFirstActionPerformed

    private void txtFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstActionPerformed

    private void txtSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecondActionPerformed

    private void txtThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThirdActionPerformed

    private void txtFifthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFifthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFifthActionPerformed

    private void txtFourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFourthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFourthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmakingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmakingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmakingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmakingapizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmakingapizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JLabel lblEighth;
    private javax.swing.JLabel lblEleventh;
    private javax.swing.JLabel lblFifth;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFourth;
    private javax.swing.JLabel lblNinth;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblSeventh;
    private javax.swing.JLabel lblSixth;
    private javax.swing.JLabel lblTenth;
    private javax.swing.JLabel lblThird;
    private javax.swing.JLabel lblTwelfth;
    private javax.swing.JTextField txtFifth;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtFourth;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtThird;
    // End of variables declaration//GEN-END:variables
}
